export const EDIT_PROFILE_FORM_SUBMIT = 'EDIT_PROFILE_FORM_SUBMIT';
export const EDIT_PROFILE_FORM_SUBMIT_SUCCESS = 'EDIT_PROFILE_FORM_SUBMIT_SUCCESS';
export const EDIT_PROFILE_FORM_SUBMIT_FAILED = 'EDIT_PROFILE_FORM_SUBMIT_FAILED';


export function editProfile(form) {

}
