export const ORDER_INFO = {
  id: '034536',
};

export const CONSTRUCTOR_DATA = [
  {
    "_id":"60666c42cc7b410027a1a9b1",
    "name":"Краторная булка N-200i",
    "type":"bun",
    "proteins":80,
    "fat":24,
    "carbohydrates":53,
    "calories":420,
    "price":1255,
    "image":"https://code.s3.yandex.net/react/code/bun-02.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9bf",
    "name":"Сыр с астероидной плесенью",
    "type":"main",
    "proteins":84,
    "fat":48,
    "carbohydrates":420,
    "calories":3377,
    "price":4142,
    "image":"https://code.s3.yandex.net/react/code/cheese.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/cheese-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/cheese-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9b5",
    "name":"Говяжий метеорит (отбивная)",
    "type":"main",
    "proteins":800,
    "fat":800,
    "carbohydrates":300,
    "calories":2674,
    "price":3000,
    "image":"https://code.s3.yandex.net/react/code/meat-04.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9be",
    "name":"Мини-салат Экзо-Плантаго",
    "type":"main",
    "proteins":1,
    "fat":2,
    "carbohydrates":3,
    "calories":6,
    "price":4400,
    "image":"https://code.s3.yandex.net/react/code/salad.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/salad-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/salad-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9b8",
    "name":"Соус фирменный Space Sauce",
    "type":"sauce",
    "proteins":50,
    "fat":22,
    "carbohydrates":11,
    "calories":14,
    "price":80,
    "image":"https://code.s3.yandex.net/react/code/sauce-04.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/sauce-04-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9bc",
    "name":"Плоды Фалленианского дерева",
    "type":"main",
    "proteins":20,
    "fat":5,
    "carbohydrates":55,
    "calories":77,
    "price":874,
    "image":"https://code.s3.yandex.net/react/code/sp_1.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/sp_1-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/sp_1-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9b6",
    "name":"Биокотлета из марсианской Магнолии",
    "type":"main",
    "proteins":420,
    "fat":142,
    "carbohydrates":242,
    "calories":4242,
    "price":424,
    "image":"https://code.s3.yandex.net/react/code/meat-01.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/meat-01-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/meat-01-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9b9",
    "name":"Соус традиционный галактический",
    "type":"sauce",
    "proteins":42,
    "fat":24,
    "carbohydrates":42,
    "calories":99,
    "price":15,
    "image":"https://code.s3.yandex.net/react/code/sauce-03.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/sauce-03-large.png",
    "__v":0
  },
  {
    "_id":"60666c42cc7b410027a1a9b5",
    "name":"Говяжий метеорит (отбивная)",
    "type":"main",
    "proteins":800,
    "fat":800,
    "carbohydrates":300,
    "calories":2674,
    "price":3000,
    "image":"https://code.s3.yandex.net/react/code/meat-04.png",
    "image_mobile":"https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    "image_large":"https://code.s3.yandex.net/react/code/meat-04-large.png",
    "__v":0
  },
]