export const SET_CORRECT_ORDERS: 'SET_CORRECT_ORDERS' = 'SET_CORRECT_ORDERS';
export const SET_DONE_ORDERS: 'SET_DONE_ORDERS' = 'SET_DONE_ORDERS';
export const SELECT_ORDER: 'SELECT_ORDER' = 'SELECT_ORDER';
export const UNSELECT_ORDER: 'UNSELECT_ORDER' = 'UNSELECT_ORDER';

