export const FORGOT_PASSWORD_FORM_SUBMIT: 'FORGOT_PASSWORD_FORM_SUBMIT' = 'FORGOT_PASSWORD_FORM_SUBMIT';
export const FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS: 'FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS' = 'FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS';
export const FORGOT_PASSWORD_FORM_SUBMIT_FAILED: 'FORGOT_PASSWORD_FORM_SUBMIT_FAILED' = 'FORGOT_PASSWORD_FORM_SUBMIT_FAILED';
export const FORGOT_PASSWORD_RESET: 'FORGOT_PASSWORD_RESET' = 'FORGOT_PASSWORD_RESET';