export const LOGIN_FORM_SUBMIT: 'LOGIN_FORM_SUBMIT' = 'LOGIN_FORM_SUBMIT';
export const LOGIN_FORM_SUBMIT_SUCCESS: 'LOGIN_FORM_SUBMIT_SUCCESS' = 'LOGIN_FORM_SUBMIT_SUCCESS';
export const LOGIN_FORM_SUBMIT_FAILED: 'LOGIN_FORM_SUBMIT_FAILED' = 'LOGIN_FORM_SUBMIT_FAILED';