export const PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST' = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS' = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILED: 'PLACE_ORDER_FAILED' = 'PLACE_ORDER_FAILED';

export const OPEN_ORDER_DETAILS_MODAL: 'OPEN_ORDER_DETAILS_MODAL' = 'OPEN_ORDER_DETAILS_MODAL';
export const CLOSE_ORDER_DETAILS_MODAL: 'CLOSE_ORDER_DETAILS_MODAL' = 'CLOSE_ORDER_DETAILS_MODAL';